言語の追加
TarochanChannel/Kana-dictionary pull request #5
Opened 2021-08-28 02:56 UTC by HidemaruOwO

2021-09-01 09:31 UTC, TarochanChannel commented
JSONの記法を守ってください

2021-11-03 06:49 UTC, waki285 requested changes
書き方の修正をレビューしておきました @TarochanChannel

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```
jsonにメモはつけられません

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ],
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    "content": "PHPは "The PHP Group" によってコミュニティベースで開発されているオープンソースの汎用プログラミング言語およびその公式の処理系であり、特にサーバーサイドで動的なウェブページを作成するための機能を多く備えていることを特徴とする。"
```suggestion
    "content": "PHPは \"The PHP Group\" によってコミュニティベースで開発されているオープンソースの汎用プログラミング言語およびその公式の処理系であり、特にサーバーサイドで動的なウェブページを作成するための機能を多く備えていることを特徴とする。"
```
エスケープ

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ],
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ],
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 06:49 UTC, waki285 commented on kanationary.json
> +    ], //コピペテンプレート
```suggestion
    ], 
```

2021-11-03 07:31 UTC, merged